languageCode = "en-us"
title = "Kraken Tutors"
baseURL = "/"
themesDir = "themes"
theme = "hugo-hero-theme"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"
    
[params]
  google_analytics_id="G-P1M8FBZ1ZC"
  siteName = "Kraken"

  [params.homepage_meta_tags]
    meta_description = "Kraken Tutors, an apprentice-based learning method for programming. Based out of Hamilton/Toronto region."
    meta_og_title = "Kraken Tutors"
    meta_og_type = "website"
    meta_og_url = "https://krakentutors.ca"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-hero-theme/master/images/tn.png"
    meta_og_description = "Kraken Tutors, an apprentice-based learning method for programming"
    meta_twitter_card = "summary"
    meta_twitter_site = "@zerostaticio"
    meta_twitter_creator = "@zerostaticio"

[[menu.main]]
	name = "Services"
	url = "/services/"
    weight = 1

[[menu.main]]
    name = "Work"
    url = "/work/"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3


[[menu.main]]
    name = "History"
    url = "/history/"
    weight = 3

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
